language: node_js
sudo: false
node_js:
- '8.9.1'
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_9bffcfc3f812_key -iv $encrypted_9bffcfc3f812_iv
  -in .travis/id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config
- git config --global user.name 'andot'
- git config --global user.email 'mabingyao@gmail.com'
install:
- npm install hexo-cli -g
- npm install
script:
- hexo cl && hexo g -d
cache:
  directories:
  - node_modules
